---
abstract: 'Encode/Decode Fiber Channel World Wide Names'
author:
  - 'Jason Kohles C<< <email@jasonkohles.com> >>'
build_requires:
  Test::More: 0
  Test::Most: 0
  ok: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-WWN
no_index:
  directory:
    - inc
    - t
requires:
  Carp::Clan::Share: 0
  Device::OUI: 0
  Module::Find: 0
  Moose: 0
  Sub::Exporter: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
